version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "constellation-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5sgt0dgtvatj"
s3_prefix = "constellation-sam"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
